### ISSUE TITLE
Shows constantly in solo shuffle

### ISSUE THREAD

**Issue by SyniRon** [rbgdevx/auto-body-res#3]
In solo shuffle after the first round it shows permanently and even stays after leaving the shuffle
<img width="778" alt="image" src="https://github.com/user-attachments/assets/e5c137c6-c489-4419-b8ff-dbf845e2cfaf">

<img width="432" alt="image" src="https://github.com/user-attachments/assets/8724be3a-56d8-4a19-b62f-385915712c5b">

**Comment by rbgdevx** [comment]
Thank you for discovering that! that's actually hilarious but annoying im sure.

Ill be honest and say i've only ever played Battlegrounds and never tested in arena lol, will fix this week asap!!

**Comment by rbgdevx** [comment]
Let me know if you run into that issue again or not @SyniRon.

**Comment by SyniRon** [comment]
Confirmed fixed, thanks!
